# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kyper < Formula
  desc "CLI for the Kyper marketplace"
  homepage "https://kyper.shop"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.3.0/kyper-cli_darwin_amd64.tar.gz"
      sha256 "9ff9facec91f17cd4ad2d167b8b1aa594f669f29930895b07556b274c5dc976b"

      define_method(:install) do
        bin.install "kyper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.3.0/kyper-cli_darwin_arm64.tar.gz"
      sha256 "8537736cdc802e66a14d490c1befd77f9e75b65ee00d4057c5d11386700a000c"

      define_method(:install) do
        bin.install "kyper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.3.0/kyper-cli_linux_amd64.tar.gz"
      sha256 "6bb75f5c59023ed2a81f0a66faa06256cd4295e1b5aca8152845e79c3b55498d"
      define_method(:install) do
        bin.install "kyper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.3.0/kyper-cli_linux_arm64.tar.gz"
      sha256 "455991163282a65f38fc1320c6c19db47120451c8856815d69d14f5cf8f3a179"
      define_method(:install) do
        bin.install "kyper"
      end
    end
  end
end
