# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kyper < Formula
  desc "CLI for the Kyper marketplace"
  homepage "https://kyper.shop"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.5.2/kyper-cli_darwin_amd64.tar.gz"
      sha256 "a513087fea213b509b036b2f7234968d1e95ef4b9826424f300b91fa8874e55e"

      define_method(:install) do
        bin.install "kyper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.5.2/kyper-cli_darwin_arm64.tar.gz"
      sha256 "f16d2d80d2d78829c09214709b1faa323cd52856ed0b87b1fd757a17f6fe7c94"

      define_method(:install) do
        bin.install "kyper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.5.2/kyper-cli_linux_amd64.tar.gz"
      sha256 "ed7942c2b7cb3063bfecd8f7bbe6142d294eef6b8e875a64fed28d2adbf723fd"
      define_method(:install) do
        bin.install "kyper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitfootco/kyper-cli/releases/download/v0.5.2/kyper-cli_linux_arm64.tar.gz"
      sha256 "6a074148435aaf4bb81b1a6ba6e84f3315d8ee499edca118991097594ee2bc4a"
      define_method(:install) do
        bin.install "kyper"
      end
    end
  end
end
